#!/bin/bash

echo "=== MCP Architecture Demo ==="
echo ""
echo "The MCP (Model Context Protocol) provides three usage modes:"
echo ""

echo "1. THIN CLIENT MODE (mcp-test command)"
echo "   - Client does NOT load any index"
echo "   - Spawns server subprocess that loads the index"
echo "   - Good for testing MCP protocol"
echo ""
echo "   Example:"
echo "   $ cargo run -- mcp-test"
echo ""

echo "2. EMBEDDED MODE (mcp command)"  
echo "   - No separate process"
echo "   - Direct tool calls on already-loaded index"
echo "   - Most efficient for CLI usage"
echo "   - No protocol overhead"
echo ""
echo "   Example:"
echo "   $ cargo run -- mcp find_symbol --args '{\"name\": \"main\"}'"
echo ""

echo "3. STANDALONE SERVER MODE (serve command)"
echo "   - Long-running server process"
echo "   - Loads index once, serves many clients"
echo "   - For AI assistants (Claude, etc)"
echo "   - Most efficient for production"
echo ""
echo "   Example:"
echo "   Terminal 1: $ cargo run -- serve"
echo "   Terminal 2: $ npx @modelcontextprotocol/inspector cargo run -- serve"
echo ""

echo "Memory Usage:"
echo "- Thin Client: 2 processes (client minimal, server has index)"
echo "- Embedded: 1 process (CLI with index)"
echo "- Standalone: 1 server process + N thin clients"